### ISSUE TITLE
Pompe #3

### ISSUE THREAD

**Issue by tomlev** [mika-nt28/Jeedom-balboa#21]
Bonjour,

Je viens d'installer le plugin qui fonctionne au top, par contre mon spa dispose de 3 pompes. Pourriez-vous ajouter la 3ème pompe pour le contrôle+statut ? (peut-être avec une option sur l'équipement ?)

Cdt

**Comment by mika-nt28** [comment]
Je vais regarder ca
J'aurrais peut etre besoin de quelques log car je n'ai pas la documentation des autres pompes

**Comment by mika-nt28** [comment]
J'ai ajouté sur la beta #23 cette possibilité.
Est ce possible d'installer la version beta afin de faire un test car j'ai suivie un logique d’incrémentation pour l’état de la pompe et sa commande, mais je n'ai pas de documentation sur le sujet

**Comment by tomlev** [comment]
Merci pour le retour (et désolé pour mon délai de réponse, ce sont les vacances ^^)
Je n'ai jamais installé de plugin en bêta, quelle est la procédure ? Cela remet-il en cause le support jeedom ?
Remarque subsidiaire : sur l'app balboa iOS il est possible de déclencher manuellement la pompe de circulation, je ne vois pas l'équivalent via le plugin, pensez-vous que ça soit possible ?

**Comment by mika-nt28** [comment]
La modification a ete entre temps poussé en stable
Pour l'activation de la pompe de circu je ne sais pas.
Si c'est possible sur une appli balboa il n'y a pas de raison que se ne soi pas possible via le plugin 
Faut que l'on retrouve la bonne trame a envoyé

**Comment by tomlev** [comment]
super nouvelle je vais regarder ça.
merci @mika-nt28 ;)

**Comment by tomlev** [comment]
ça fonctionne au top, merci !
J'ai par contre du modifier le json envoyé au moment de l'ajout de la commande car jeedom indiquait que le type de la commande était vide. (type=action,subType=other)
La commande de la pompe de circulation qui apparait sur l'app balboa est-elle gérée sur le plugin, si oui quelle est le choix à faire ?

**Comment by mika-nt28** [comment]
Super bonne nouvelle
Je vais regarder ce probleme de type et sous type

Pour la commande de pompe de circu je ne sais pas trop quel commande envoyé car il n'y a a premiere vue pas de logique contrairement a la pompe 3 4 et 5
J'ai ajouté au code mais je ne sais pas si je l'ai ajouté a la liste des choix
