### ISSUE TITLE
Trop de notifications pour erreur de communication

### ISSUE THREAD

**Issue by tomlev** [mika-nt28/Jeedom-balboa#40]
Bonjour,

Après quelques mois d'utilisation tout marche parfaitement ;)
J'ai néanmoins une demande qui m'arrangerait bien : je me retrouve avec ENORMEMENT de notifications jeedom de ce genre 
Erreur sur balboa::pull() : [Spa][Spa] Impossible de se connecter => 192.168.0.171:4257

Parfois quelques centaines en quelques jours ^^
Je suppose que l'équipement wifi du spa doit se déconnecter de mon routeur de temps en temps. 
Pourtant c'est un routeur pro, situé à quelques mètres du spa.
Ces décos ne gênent en rien la remontée d'informations au fur et à mesure de la journée (la température ne varie pas super vite lol), ce serait donc top de trouver une solution pour remonter moins d'alertes qui polluent mes logs jeedom. D'ailleurs même en niveau de log=aucun j'ai ces alertes :/

-> Sur le cron de mise à jour du coup peut être ajouter un timestamp de dernière update réussie, et n'envoyer l'alerte que si celle-ci est trop ancienne lorsqu'on rencontre une erreur ?

**Comment by mika-nt28** [comment]
Merci de passé sur community pour toute demande de support .
Pour l'erreur remonté je pense avoir une piste.
Le plugin se connect au SPA plusieurs fois dans le code (en fonction de la demande)
Si les connexion sont simultané je ne suis pas sur que le SPA l'accept et on as cette erreur
